from fastapi import APIRouter, Depends, HTTPException, status
from app.core.dependencies import get_current_user
from app.db.supabase_client import get_supabase_admin

router = APIRouter(prefix="/missions", tags=["Missions"])


@router.get("/")
async def get_missions(user: dict = Depends(get_current_user)):
    """Get all active missions for the user."""
    supabase = get_supabase_admin()
    result = (
        supabase.table("user_missions")
        .select("*")
        .eq("user_id", user["id"])
        .in_("status", ["pending", "active"])
        .execute()
    )
    return {"missions": result.data or []}


@router.post("/{mission_id}/complete")
async def complete_mission(mission_id: str, user: dict = Depends(get_current_user)):
    """Mark a mission as completed and add XP."""
    supabase = get_supabase_admin()
    
    mission = supabase.table("user_missions").select("*").eq("id", mission_id).eq("user_id", user["id"]).single().execute()
    if not mission.data:
        raise HTTPException(status_code=404, detail="Mission not found")
        
    if mission.data.get("status") == "completed":
        return {"success": True, "message": "Mission already completed"}

    supabase.table("user_missions").update({"status": "completed"}).eq("id", mission_id).execute()
    
    xp_reward = mission.data.get("xp_reward", 0)
    if xp_reward > 0:
        new_xp = user.get("total_xp", 0) + xp_reward
        supabase.table("users").update({"total_xp": new_xp}).eq("id", user["id"]).execute()
        
    return {"success": True, "xp_earned": xp_reward}


@router.post("/{mission_id}/rollover")
async def rollover_mission(mission_id: str, user: dict = Depends(get_current_user)):
    """Keep a mission pending for the next cycle."""
    supabase = get_supabase_admin()
    
    mission = supabase.table("user_missions").select("*").eq("id", mission_id).eq("user_id", user["id"]).single().execute()
    if not mission.data:
        raise HTTPException(status_code=404, detail="Mission not found")
        
    rollover_count = mission.data.get("rollover_count", 0) + 1
    supabase.table("user_missions").update({"rollover_count": rollover_count, "status": "active"}).eq("id", mission_id).execute()
    
    return {"success": True, "message": "Mission rolled over"}


@router.post("/{mission_id}/replace")
async def replace_mission(mission_id: str, user: dict = Depends(get_current_user)):
    """Replace an impossible mission with a new one generated by AI."""
    supabase = get_supabase_admin()
    
    mission = supabase.table("user_missions").select("*").eq("id", mission_id).eq("user_id", user["id"]).single().execute()
    if not mission.data:
        raise HTTPException(status_code=404, detail="Mission not found")
        
    supabase.table("user_missions").update({"status": "skipped"}).eq("id", mission_id).execute()
    
    # Mocking generation of a new mission for now
    new_mission_data = {
        "user_id": user["id"],
        "title": "Nueva misión (Reemplazo)",
        "description": "El coach ha adaptado esta misión para ti.",
        "xp_reward": 50,
        "difficulty": "Media",
        "status": "active"
    }
    
    result = supabase.table("user_missions").insert(new_mission_data).execute()
    return {"success": True, "new_mission": result.data[0] if result.data else None}
